### PR TITLE
Kubernetes worker improvements

### PR DESCRIPTION
**Pull request by ghjm**
* Combine `newWorker()` with `Init()` to provide the initialization behavior the k8s worker needs
* Add k8s auth from provided parameters as well as kubeconfig files

### CODE REVIEW

**Comment by ghjm** [comment]
There's still more work to be done on this, but I think this is a good point where we can merge the work so far.

What this includes:

* We have the concept of secret fields.  Units now have a new `UnredactedStatus()` function.  `Status()` now returns status data with any secrets blanked out.  `UnredactedStatus()` returns the full data including secrets.
* The command service `work submit` function will return an error if you try to submit a command including JSON parameters that start with `secret_`, but you are proposing to send them over a non-TLS connection to a remote node.
* The remote worker's `work submit` implementation now always uses JSON commands to start the work on the remote node.
* The `SetParamsAndSave` function now only sets params, to allow decoupling of the param setting from the saving.  Also, it is now named `SetFromParams` to better reflect what's happening (the object is being set from the provided params).
* Receptorctl is updated to include the ability to provide arbitrary parameters to a work submittal via `--param/-a`.

Still to be done (outside the scope of this PR):

* Add a mode where the worker pod communicates with Receptor by cluster-local TCP instead of through the slow and problematic k8s spdy/logger implementation.
* Encryption at rest of status/stdout data.

**Review by fosterseth — APPROVED** [review]

**Review by squidboylan — APPROVED** [review]

**Comment by fosterseth** [comment]
Tried this out with a local minikube setup

everything mostly worked fine, except I got a hang when trying the following (I see the pod is created and running, but it never terminates)

```yaml
- work-kubernetes:
    worktype: kubeit
    namespace: default
    command: "bash -c \"while read -r line; do echo $line; sleep 0.5; done\""
    authmethod: params
    kubehost: http://127.0.0.1:44355/
    kubeapipath: api/v1
    kubeusername: sbf
    kubepassword: sbf
    allowruntimecommand: true
```
`seq 10 | receptorctl --socket /tmp/foo.sock work submit kubeit --payload - -f --param kube_image=centos:8 --rm`

if I add in my own `kube_command` it will work

`seq 10 | receptorctl --socket /tmp/foo.sock work submit kubeit --payload - -f --param kube_image=centos:8 --rm --param kube_command='echo HI'`

also if I change `authmethod` to `kubeconfig` it will work

```yaml
- work-kubernetes:
    worktype: kubeit
    namespace: default
    command: "bash -c \"while read -r line; do echo $line; sleep 0.5; done\""
    kubeconfig: /home/sfoster/.kube/config
    authmethod: kubeconfig
    allowruntimecommand: true
```

Maybe I am missing some detail?

**Comment by ghjm** [comment]
I wasn't able to reproduce this - in my environment the first example works.  But I am using CRC rather than minikube.

I have seen a couple times when we didn't get any results until the whole process finished, then we get them all at once at the end.  The delay seemed to be happening in the k8s logger, not in Receptor.  Is there any chance this is what's going on for you - i.e. did you wait long enough that the whole process could have finished?  Also, when you see the container running, does it go to a finished state or does it stay in running?

**Comment by fosterseth** [comment]
staying in running state

```
[sfoster@localhost ghjm]$ kubectl get pods
NAME           READY   STATUS    RESTARTS   AGE
kubeit-tvp6s   1/1     Running   0          3m58s
```
from describe

```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  4m30s  default-scheduler  Successfully assigned default/kubeit-tvp6s to minikube
  Normal  Pulled     4m29s  kubelet, minikube  Container image "centos:8" already present on machine
  Normal  Created    4m29s  kubelet, minikube  Created container worker
  Normal  Started    4m29s  kubelet, minikube  Started container worker
```

**Comment by ghjm** [comment]
I wonder if it's not getting stdin?

**Comment by fosterseth** [comment]
hmm you might be right, given my echo command works fine in those cases

**Comment by ghjm** [comment]
So then the question is whether Receptor is failing to pass the stdin, or if it's getting to the Kube API but not making it to the actual container.

**Comment by ghjm** [comment]
Merging this as is for now, will deal with the stdin issue (if that's what it is) in a future PR

**Pull request merged**
