### PR TITLE
add delay backoff for redial in backends

### PR DESCRIPTION
**Pull request by fosterseth**
issue #137

### CODE REVIEW

**Comment by squidboylan** [comment]
We should start our tcp, udp, websocket redials at a much quicker interval, maybe 100ms?

**Comment by ghjm** [comment]
I see where that makes sense in the test context, but it seems a little aggressive in the real-world context, at least with a 1.5 backoff multiplier.  We'd be making 5 attempts within the first second.

**Comment by ghjm** [comment]
Also, we have this same retry logic in multiple places in the code now.  Should we make a retry interval calculator in utils, and use it from all the places that are doing retries with backoffs?

**Comment by fosterseth** [comment]
@ghjm 
I created a `util.IncreaseDuration()` function to handle increasing time.Duration up to a max. Is this what you had in mind?

**Comment by ghjm** [comment]
I was vaguely thinking of a struct that holds the current, multiplier and limit values and has a NextDelay method, but it's not that big a deal.

**Comment by fosterseth** [comment]
@ghjm ok I went ahead and implemented it as an `IncrementalDuration` struct with a `NextDelay()` method

**Review by ghjm — APPROVED** [review]

**Pull request merged**
