### PR TITLE
Convert convertible values properly 

### PR DESCRIPTION
**Pull request by ghjm**
When the cmdline library is given a value which is convertible to the field's target type, it attempts to set it directly.  This results in a panic when the value is convertible but not directly assignable, such as when assigning an integer to a float field.  To fix this, we actually do the conversion, which we know will succeed because we just checked for convertibility.

See https://github.com/project-receptor/receptor/issues/104.

### CODE REVIEW

**Comment by squidboylan** [comment]
This fixes the issue for `cost` but not `nodecost`:

```
panic: reflect.Value.SetMapIndex: value of type int is not assignable to type float64
goroutine 1 [running]:
reflect.Value.assignTo(0x14b8a20, 0xc00029e600, 0x82, 0x1700408, 0x19, 0x1495ce0, 0x0, 0x14bbc20, 0xc0002d8f60, 0x98)
        /usr/local/go/src/reflect/value.go:2411 +0x426
reflect.Value.SetMapIndex(0x151c8a0, 0xc000398780, 0x15, 0x14bbc20, 0xc0002d8f60, 0x98, 0x14b8a20, 0xc00029e600, 0x82)
        /usr/local/go/src/reflect/value.go:1674 +0x1db
github.com/project-receptor/receptor/pkg/cmdline.setValue(0xc0001e3820, 0x151a2c0, 0xc000398600, 0xc0001e3820, 0x0)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:218 +0x885
github.com/project-receptor/receptor/pkg/cmdline.loadConfigFromFile(0x7ffcb07c15b6, 0x8, 0x7ffcb07c15b6, 0x8, 0xc0001d5dc8, 0x203000, 0x40deb6)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:448 +0x551
github.com/project-receptor/receptor/pkg/cmdline.ParseAndRun(0xc00003c190, 0x2, 0x2)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:517 +0x104f
main.main()
        /home/squid/work/project-receptor/receptor/cmd/receptor.go:60 +0x33c
```

**Comment by ghjm** [comment]
@squidboylan thanks for catching that.  The updated code should work correctly with maps and slices.

**Comment by squidboylan** [comment]
I think we're getting close, the config file seems to work as intended now, however the cli no `nodecost` longer works:

```
squid@localhost:~/work/project-receptor/receptor$ receptor --node id=foo --tcp-listener nodecost='{"bar": 1.0}' port=10000
panic: reflect: call of reflect.Value.Elem on string Value

goroutine 1 [running]:
reflect.Value.Elem(0x14bbc20, 0xc0002d8d80, 0x98, 0x98, 0x1495ce0, 0xc00029e5c8)
        /usr/local/go/src/reflect/value.go:827 +0x1a4
github.com/project-receptor/receptor/pkg/cmdline.setValue(0xc0001e37a0, 0x14bbc20, 0xc0002d8d10, 0xc0001e37a0, 0x0)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:226 +0xabf
github.com/project-receptor/receptor/pkg/cmdline.ParseAndRun(0xc00003c1f0, 0x5, 0x5)
        /home/squid/work/project-receptor/receptor/pkg/cmdline/cmdline.go:577 +0x93e
main.main()
        /home/squid/work/project-receptor/receptor/cmd/receptor.go:60 +0x33c
```

this used to work but no longer does

**Comment by ghjm** [comment]
Should work now @squidboylan

**Review by squidboylan — APPROVED** [review]
Yep seems to work now :tada: Thanks!

**Pull request merged**
