### PR TITLE
adding workflow_dispatch trigger to github CI

### PR DESCRIPTION
**Pull request by sarabrajsingh**
this small change will allow us to re-run jobs in github actions

### CODE REVIEW

**Comment by shanemcd** [comment]
There's already a way to do this:

receptor@ca1bc69 2022-02-04 10-12-28

**Comment by shanemcd** [comment]
I also think the way you have set this up would always clone devel.

**Comment by sarabrajsingh** [comment]
> I also think the way you have set this up would always clone devel.

@shanemcd looks like the problems are occuring because i'm working on an out-of-date version of my fork. I'll try re-baseing the fork on my end to see if it helps

**Comment by sarabrajsingh** [comment]
> I also think the way you have set this up would always clone devel.

@shanemcd looks like the problems are occuring because i'm working on an out-of-date version of my fork. I'll try re-baseing the fork on my end to see if it helps

**Pull request closed without merging**
