### PR TITLE
Add coverage reports to all PRs

### PR DESCRIPTION
**Pull request by AaronH88**
Add support for codecov and display code coverage reports for all PRs.

### CODE REVIEW

**Comment by AaronH88** [comment]
As this is the base PR codecov has nothing to compare the coverage results against, but as we can see in both the details of `CI/receptor` and the codecov UI, the coverage results were successfully generated and uploaded.

**Comment by shanemcd** [comment]
Can you add the codecov badge to the readme?

**Comment by AaronH88** [comment]
> Can you add the codecov badge to the readme?

Added right at the top under Receptor as I have seen similar in other projects. Feel free to suggest alternative placements :smile:

**Comment by AaronH88** [comment]
No comments here in a while, im assuming its ok to merge :smile:

**Pull request merged**
