### PR TITLE
Add .github/dependabot.yml

### PR DESCRIPTION
**Pull request by eqrx**
This instructs GH dependabot to monitor outdated dependencies
in this repo and open PRs to upgrade them.

### CODE REVIEW

**Comment by shanemcd** [comment]
@eqrx Thanks for the PR. Have you merged this into devel on your fork and observed the behavior? I'm a little nervous about getting more PRs than we can react to, especially while our tests are still flaky.

**Comment by eqrx** [comment]
@shanemcd no I have not. Mainly because per default dependabot does not create PRs in forks. But I am using it in my personal projects.

Per default it creates at most 10 PRs per eco-system (go, and github-actions are the ecosystems configured). It is possible to reduce the number! So one could always set this to one

**Comment by shanemcd** [comment]
Hmmm... I just saw this https://github.com/dependabot/dependabot-core/issues/2804

I pushed your commit to devel on my branch and it is creating PRs: https://github.com/shanemcd/receptor/pulls

Will take a look in the morning to see how they go.

**Comment by shanemcd** [comment]
It looks like 3 out of 5 failed, but 2 of those failures were GHA flake while uploading the archived binary.

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
